
default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: <%= ENV['mysql_username']%>
  password: <%= ENV['mysql_password']%>
  socket: /var/run/mysqld/mysqld.sock

development:
  <<: *default
  database: ticketee_development

test:
  <<: *default
  database: ticketee_test

production:
  <<: *default
  database: ticketee_production
  username: ticketee
  password: <%= ENV['TICKETEE_DATABASE_PASSWORD'] %>
